### ISSUE TITLE
Working with Raspberry pi 0?

### ISSUE THREAD

**Issue by alexkid64** [kevineye/docker-airplay-to-bluetooth#1]
Hi,

I'm trying your work with an rapberry pi 0 with hyprit, and unfortunatly it does'nt work.
Could you help me? I'm new with docker solution

thanks in advance

Alex

**Comment by kevineye** [comment]
This docker image is for x86 processors, so it won't work with the Raspberry Pi's ARM processor. This is typical for docker images -- I know there is a vibrant Raspberry PI Docker community, but unless an image mentions the pi or ARM processors, it probably won't work.

You might be able to modify this image's Dockerfile to build from an arm-compatible base image, like easypi/alpine-arm. I have not tried this.

**Comment by alexkid64** [comment]
I will try, thanks for your reply
